DROP DIRECTORY ext_file_ds;
CREATE OR REPLACE DIRECTORY ext_file_ds AS 'C:\Data\CSV';
GRANT ALL ON DIRECTORY ext_file_ds TO PUBLIC;
SELECT * FROM all_directories;

DROP TABLE EXPEDITORI;
CREATE TABLE EXPEDITORI (
    id_expeditor NUMBER,
    nume VARCHAR2(50),
    prenume VARCHAR2(50),
    cod_postal NUMBER,
    adresa VARCHAR2(100),
    nr_telefon VARCHAR2(10)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY ext_file_ds
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE SKIP 1
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('2_EXPEDITORI.csv')
)
REJECT LIMIT UNLIMITED;

SELECT * FROM EXPEDITORI;