ROLLBACK;
ALTER SESSION CLOSE DATABASE LINK colete;

DROP DATABASE LINK colete;
CREATE DATABASE LINK colete
   CONNECT TO colete IDENTIFIED BY colete
   USING '//localhost:1521/XEPDB1';

select * from user_db_links;

----------------------------
DROP VIEW TRANSPORTURI_VIEW;
CREATE OR REPLACE VIEW TRANSPORTURI_VIEW AS
SELECT ID_TRANSPORT,ID_DEPOZIT,ID_SOFER,ID_VEHICUL,DATA_PLECARE,ORA_PLECARE,DATA_SOSIRE,ORA_SOSIRE,INCIDENTE,KM_PARCURSI,COMBUSTIBIL_CONSUMAT
FROM transporturi@colete;

select * from TRANSPORTURI_VIEW;